name: Continuous Test Run

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Run Tests
        run: go test -v -race -count=1 -timeout 10m -failfast ./...